# Generated by Django 4.2.7 on 2023-11-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(db_index=True, max_length=12, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
